#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'soundbot'


Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end


begin
  Soundbot::Config.set_default_config
  settings = Soundbot::Config.load_config
  puts "#{settings[:library]}"
rescue Soundbot::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
